/**
 * Generated by orval v7.17.2 🍺
 * Do not edit manually.
 * Diet Management System API
 * 
# Diet Management System API Documentation

Clean Architecture + DDD + CQRS prensipleriyle inşa edildi. Üretim güvenliği için Helmet, oran sınırlama, doğrulama ve problem-details hata yapısı uygulanmıştır.

Authentication: JWT Bearer.
- Authorization header: `Bearer <token>`
- /auth/login haricindeki tüm endpoint’ler token ister.

 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

export type RegisterDtoRole = typeof RegisterDtoRole[keyof typeof RegisterDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RegisterDtoRole = {
  ADMIN: 'ADMIN',
  DIETITIAN: 'DIETITIAN',
  CLIENT: 'CLIENT',
} as const;

export interface RegisterDto {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
  role?: RegisterDtoRole;
}

export type RegisterResponseDtoUser = { [key: string]: unknown };

export interface RegisterResponseDto {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: RegisterResponseDtoUser;
}

export interface LoginDto {
  email: string;
  password: string;
}

export type LoginResponseDtoUser = { [key: string]: unknown };

export interface LoginResponseDto {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
  user: LoginResponseDtoUser;
}

export interface RefreshTokenDto {
  refreshToken: string;
}

export interface RefreshTokenResponseDto {
  accessToken: string;
  refreshToken: string;
  expiresIn: number;
}

export type CreateUserDtoRole = typeof CreateUserDtoRole[keyof typeof CreateUserDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateUserDtoRole = {
  ADMIN: 'ADMIN',
  DIETITIAN: 'DIETITIAN',
  CLIENT: 'CLIENT',
} as const;

export interface CreateUserDto {
  email: string;
  /** @minLength 8 */
  password: string;
  firstName: string;
  lastName: string;
  role: CreateUserDtoRole;
}

export type UserResponseDtoRole = typeof UserResponseDtoRole[keyof typeof UserResponseDtoRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserResponseDtoRole = {
  ADMIN: 'ADMIN',
  DIETITIAN: 'DIETITIAN',
  CLIENT: 'CLIENT',
} as const;

export interface UserResponseDto {
  id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: UserResponseDtoRole;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface UpdateUserDto {
  email?: string;
  firstName?: string;
  lastName?: string;
}

export type CreateClientDtoGender = typeof CreateClientDtoGender[keyof typeof CreateClientDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateClientDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;

export interface CreateClientDto {
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  dateOfBirth?: string;
  gender?: CreateClientDtoGender;
  dietitianId: string;
  allergies?: string[];
  conditions?: string[];
  medications?: string[];
  notes?: string;
}

export type ClientResponseDtoGender = typeof ClientResponseDtoGender[keyof typeof ClientResponseDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ClientResponseDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;

export interface ClientResponseDto {
  id: string;
  firstName: string;
  lastName: string;
  email: string;
  phone?: string;
  dateOfBirth?: string;
  gender?: ClientResponseDtoGender;
  dietitianId: string;
  allergies: string[];
  conditions: string[];
  medications: string[];
  notes?: string;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export type UpdateClientDtoGender = typeof UpdateClientDtoGender[keyof typeof UpdateClientDtoGender];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UpdateClientDtoGender = {
  MALE: 'MALE',
  FEMALE: 'FEMALE',
  OTHER: 'OTHER',
} as const;

export interface UpdateClientDto {
  firstName?: string;
  lastName?: string;
  phone?: string;
  dateOfBirth?: string;
  gender?: UpdateClientDtoGender;
  allergies?: string[];
  conditions?: string[];
  medications?: string[];
  notes?: string;
}

export interface NutritionalGoalsDto {
  targetCalories?: number;
  targetProtein?: number;
  targetCarbs?: number;
  targetFat?: number;
  targetFiber?: number;
}

export type CreateDietPlanDtoStatus = typeof CreateDietPlanDtoStatus[keyof typeof CreateDietPlanDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateDietPlanDtoStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface CreateDietPlanDto {
  name: string;
  description?: string;
  clientId: string;
  startDate: string;
  endDate?: string;
  status?: CreateDietPlanDtoStatus;
  nutritionalGoals?: NutritionalGoalsDto;
}

export type DietPlanResponseDtoStatus = typeof DietPlanResponseDtoStatus[keyof typeof DietPlanResponseDtoStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const DietPlanResponseDtoStatus = {
  DRAFT: 'DRAFT',
  ACTIVE: 'ACTIVE',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED',
} as const;

export interface DietPlanResponseDto {
  id: string;
  name: string;
  description?: string;
  clientId: string;
  dietitianId: string;
  startDate: string;
  endDate?: string;
  status: DietPlanResponseDtoStatus;
  nutritionalGoals?: NutritionalGoalsDto;
  version: number;
  isActive: boolean;
  createdAt: string;
  updatedAt: string;
}

export interface FoodResponseDto {
  name: string;
  description: string;
  category: string;
  servingSize: number;
  servingUnit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
  fiber?: number;
  sugar?: number;
  sodium?: number;
}

export interface CreateFoodDto { [key: string]: unknown }

/**
 * Time of day when the meal is scheduled
 */
export type MealResponseDtoTimeOfDay = typeof MealResponseDtoTimeOfDay[keyof typeof MealResponseDtoTimeOfDay];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MealResponseDtoTimeOfDay = {
  BREAKFAST: 'BREAKFAST',
  MORNING_SNACK: 'MORNING_SNACK',
  LUNCH: 'LUNCH',
  AFTERNOON_SNACK: 'AFTERNOON_SNACK',
  DINNER: 'DINNER',
  EVENING_SNACK: 'EVENING_SNACK',
} as const;

export interface MealResponseDto {
  /** Unique identifier of the meal */
  id: string;
  /** Meal plan ID this meal belongs to */
  mealPlanId: string;
  /** Meal name */
  name: string;
  /** Time of day when the meal is scheduled */
  timeOfDay: MealResponseDtoTimeOfDay;
  /** Description of the meal */
  description?: string;
  /** Preparation or serving instructions */
  instructions?: string;
  /** Calories count */
  calories?: number;
  /** Protein amount (grams) */
  protein?: number;
  /** Carbohydrates amount (grams) */
  carbs?: number;
  /** Fat amount (grams) */
  fat?: number;
  /** Fiber amount (grams) */
  fiber?: number;
  /** Creation timestamp */
  createdAt: string;
  /** Last update timestamp */
  updatedAt: string;
}

/**
 * Time of day
 */
export type CreateMealRequestDtoTimeOfDay = typeof CreateMealRequestDtoTimeOfDay[keyof typeof CreateMealRequestDtoTimeOfDay];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CreateMealRequestDtoTimeOfDay = {
  BREAKFAST: 'BREAKFAST',
  MORNING_SNACK: 'MORNING_SNACK',
  LUNCH: 'LUNCH',
  AFTERNOON_SNACK: 'AFTERNOON_SNACK',
  DINNER: 'DINNER',
  EVENING_SNACK: 'EVENING_SNACK',
} as const;

export interface CreateMealRequestDto {
  /** Meal plan ID */
  mealPlanId: string;
  /** Meal name */
  name: string;
  /** Time of day */
  timeOfDay: CreateMealRequestDtoTimeOfDay;
  /** Description of the meal */
  description?: string;
  /** Instructions for preparing the meal */
  instructions?: string;
  /** Calories count */
  calories?: number;
  /** Protein amount (grams) */
  protein?: number;
  /** Carbohydrates amount (grams) */
  carbs?: number;
  /** Fat amount (grams) */
  fat?: number;
  /** Fiber amount (grams) */
  fiber?: number;
}

export type UserControllerGetAllUsersParams = {
role: string;
isActive: boolean;
skip: number;
take: number;
};

export type ClientControllerGetClientsParams = {
isActive?: boolean;
skip?: number;
take?: number;
};

export type ClientControllerSearchClientsParams = {
q: string;
skip?: number;
take?: number;
};

export type DietPlanControllerGetAllDietPlansParams = {
status?: string;
isActive?: boolean;
skip?: number;
take?: number;
};

export type DietPlanControllerGetDietPlansByClientParams = {
status?: string;
isActive?: boolean;
skip?: number;
take?: number;
};

/**
 * @summary Health check endpoint
 */
export const healthControllerCheck = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<unknown>> => {
    
    
    return axios.get(
      `/api/v1/health`,options
    );
  }




export const getHealthControllerCheckQueryKey = () => {
    return [
    `/api/v1/health`
    ] as const;
    }

    
export const getHealthControllerCheckQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerCheck>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerCheckQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerCheck>>> = ({ signal }) => healthControllerCheck({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerCheckQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerCheck>>>
export type HealthControllerCheckQueryError = AxiosError<unknown>


/**
 * @summary Health check endpoint
 */

export function useHealthControllerCheck<TData = Awaited<ReturnType<typeof healthControllerCheck>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerCheck>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthControllerCheckQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Kubernetes liveness probe
 */
export const healthControllerLiveness = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/health/liveness`,options
    );
  }




export const getHealthControllerLivenessQueryKey = () => {
    return [
    `/api/v1/health/liveness`
    ] as const;
    }

    
export const getHealthControllerLivenessQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerLiveness>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerLiveness>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerLivenessQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerLiveness>>> = ({ signal }) => healthControllerLiveness({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerLiveness>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerLivenessQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerLiveness>>>
export type HealthControllerLivenessQueryError = AxiosError<unknown>


/**
 * @summary Kubernetes liveness probe
 */

export function useHealthControllerLiveness<TData = Awaited<ReturnType<typeof healthControllerLiveness>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerLiveness>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthControllerLivenessQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Kubernetes readiness probe
 */
export const healthControllerReadiness = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/health/readiness`,options
    );
  }




export const getHealthControllerReadinessQueryKey = () => {
    return [
    `/api/v1/health/readiness`
    ] as const;
    }

    
export const getHealthControllerReadinessQueryOptions = <TData = Awaited<ReturnType<typeof healthControllerReadiness>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerReadiness>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getHealthControllerReadinessQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof healthControllerReadiness>>> = ({ signal }) => healthControllerReadiness({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof healthControllerReadiness>>, TError, TData> & { queryKey: QueryKey }
}

export type HealthControllerReadinessQueryResult = NonNullable<Awaited<ReturnType<typeof healthControllerReadiness>>>
export type HealthControllerReadinessQueryError = AxiosError<unknown>


/**
 * @summary Kubernetes readiness probe
 */

export function useHealthControllerReadiness<TData = Awaited<ReturnType<typeof healthControllerReadiness>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof healthControllerReadiness>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getHealthControllerReadinessQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary User registration
 */
export const authControllerRegister = (
    registerDto: RegisterDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RegisterResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/auth/register`,
      registerDto,options
    );
  }



export const getAuthControllerRegisterMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,{data: RegisterDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,{data: RegisterDto}, TContext> => {

const mutationKey = ['authControllerRegister'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRegister>>, {data: RegisterDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRegister(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRegisterMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRegister>>>
    export type AuthControllerRegisterMutationBody = RegisterDto
    export type AuthControllerRegisterMutationError = AxiosError<void>

    /**
 * @summary User registration
 */
export const useAuthControllerRegister = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRegister>>, TError,{data: RegisterDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRegister>>,
        TError,
        {data: RegisterDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerRegisterMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary User login
 */
export const authControllerLogin = (
    loginDto: LoginDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<LoginResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/auth/login`,
      loginDto,options
    );
  }



export const getAuthControllerLoginMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginDto}, TContext> => {

const mutationKey = ['authControllerLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogin>>, {data: LoginDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerLogin(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLoginMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogin>>>
    export type AuthControllerLoginMutationBody = LoginDto
    export type AuthControllerLoginMutationError = AxiosError<void>

    /**
 * @summary User login
 */
export const useAuthControllerLogin = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogin>>, TError,{data: LoginDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogin>>,
        TError,
        {data: LoginDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerLoginMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Refresh access token
 */
export const authControllerRefreshToken = (
    refreshTokenDto: RefreshTokenDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<RefreshTokenResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/auth/refresh`,
      refreshTokenDto,options
    );
  }



export const getAuthControllerRefreshTokenMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshToken>>, TError,{data: RefreshTokenDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshToken>>, TError,{data: RefreshTokenDto}, TContext> => {

const mutationKey = ['authControllerRefreshToken'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerRefreshToken>>, {data: RefreshTokenDto}> = (props) => {
          const {data} = props ?? {};

          return  authControllerRefreshToken(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerRefreshTokenMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerRefreshToken>>>
    export type AuthControllerRefreshTokenMutationBody = RefreshTokenDto
    export type AuthControllerRefreshTokenMutationError = AxiosError<void>

    /**
 * @summary Refresh access token
 */
export const useAuthControllerRefreshToken = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerRefreshToken>>, TError,{data: RefreshTokenDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerRefreshToken>>,
        TError,
        {data: RefreshTokenDto},
        TContext
      > => {

      const mutationOptions = getAuthControllerRefreshTokenMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary User logout
 */
export const authControllerLogout = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/auth/logout`,undefined,options
    );
  }



export const getAuthControllerLogoutMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext> => {

const mutationKey = ['authControllerLogout'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof authControllerLogout>>, void> = () => {
          

          return  authControllerLogout(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuthControllerLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof authControllerLogout>>>
    
    export type AuthControllerLogoutMutationError = AxiosError<unknown>

    /**
 * @summary User logout
 */
export const useAuthControllerLogout = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof authControllerLogout>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof authControllerLogout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuthControllerLogoutMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a new user (Admin only)
 */
export const userControllerCreateUser = (
    createUserDto: CreateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/users`,
      createUserDto,options
    );
  }



export const getUserControllerCreateUserMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserDto}, TContext> => {

const mutationKey = ['userControllerCreateUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerCreateUser>>, {data: CreateUserDto}> = (props) => {
          const {data} = props ?? {};

          return  userControllerCreateUser(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerCreateUserMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerCreateUser>>>
    export type UserControllerCreateUserMutationBody = CreateUserDto
    export type UserControllerCreateUserMutationError = AxiosError<void>

    /**
 * @summary Create a new user (Admin only)
 */
export const useUserControllerCreateUser = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerCreateUser>>, TError,{data: CreateUserDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userControllerCreateUser>>,
        TError,
        {data: CreateUserDto},
        TContext
      > => {

      const mutationOptions = getUserControllerCreateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all users (Admin only)
 */
export const userControllerGetAllUsers = (
    params: UserControllerGetAllUsersParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/users`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getUserControllerGetAllUsersQueryKey = (params?: UserControllerGetAllUsersParams,) => {
    return [
    `/api/v1/users`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getUserControllerGetAllUsersQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetAllUsers>>, TError = AxiosError<unknown>>(params: UserControllerGetAllUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerGetAllUsers>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetAllUsersQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetAllUsers>>> = ({ signal }) => userControllerGetAllUsers(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetAllUsers>>, TError, TData> & { queryKey: QueryKey }
}

export type UserControllerGetAllUsersQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetAllUsers>>>
export type UserControllerGetAllUsersQueryError = AxiosError<unknown>


/**
 * @summary Get all users (Admin only)
 */

export function useUserControllerGetAllUsers<TData = Awaited<ReturnType<typeof userControllerGetAllUsers>>, TError = AxiosError<unknown>>(
 params: UserControllerGetAllUsersParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerGetAllUsers>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserControllerGetAllUsersQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get user by ID
 */
export const userControllerGetUserById = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDto>> => {
    
    
    return axios.get(
      `/api/v1/users/${id}`,options
    );
  }




export const getUserControllerGetUserByIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/users/${id}`
    ] as const;
    }

    
export const getUserControllerGetUserByIdQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetUserById>>, TError = AxiosError<void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserById>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetUserByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetUserById>>> = ({ signal }) => userControllerGetUserById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserById>>, TError, TData> & { queryKey: QueryKey }
}

export type UserControllerGetUserByIdQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetUserById>>>
export type UserControllerGetUserByIdQueryError = AxiosError<void>


/**
 * @summary Get user by ID
 */

export function useUserControllerGetUserById<TData = Awaited<ReturnType<typeof userControllerGetUserById>>, TError = AxiosError<void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerGetUserById>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserControllerGetUserByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update user
 */
export const userControllerUpdateUser = (
    id: string,
    updateUserDto: UpdateUserDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDto>> => {
    
    
    return axios.put(
      `/api/v1/users/${id}`,
      updateUserDto,options
    );
  }



export const getUserControllerUpdateUserMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUser>>, TError,{id: string;data: UpdateUserDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUser>>, TError,{id: string;data: UpdateUserDto}, TContext> => {

const mutationKey = ['userControllerUpdateUser'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof userControllerUpdateUser>>, {id: string;data: UpdateUserDto}> = (props) => {
          const {id,data} = props ?? {};

          return  userControllerUpdateUser(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UserControllerUpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof userControllerUpdateUser>>>
    export type UserControllerUpdateUserMutationBody = UpdateUserDto
    export type UserControllerUpdateUserMutationError = AxiosError<void>

    /**
 * @summary Update user
 */
export const useUserControllerUpdateUser = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof userControllerUpdateUser>>, TError,{id: string;data: UpdateUserDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof userControllerUpdateUser>>,
        TError,
        {id: string;data: UpdateUserDto},
        TContext
      > => {

      const mutationOptions = getUserControllerUpdateUserMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get current user profile
 */
export const userControllerGetCurrentUser = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<UserResponseDto>> => {
    
    
    return axios.get(
      `/api/v1/users/me/profile`,options
    );
  }




export const getUserControllerGetCurrentUserQueryKey = () => {
    return [
    `/api/v1/users/me/profile`
    ] as const;
    }

    
export const getUserControllerGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>, TError = AxiosError<void>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerGetCurrentUser>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUserControllerGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof userControllerGetCurrentUser>>> = ({ signal }) => userControllerGetCurrentUser({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof userControllerGetCurrentUser>>, TError, TData> & { queryKey: QueryKey }
}

export type UserControllerGetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof userControllerGetCurrentUser>>>
export type UserControllerGetCurrentUserQueryError = AxiosError<void>


/**
 * @summary Get current user profile
 */

export function useUserControllerGetCurrentUser<TData = Awaited<ReturnType<typeof userControllerGetCurrentUser>>, TError = AxiosError<void>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof userControllerGetCurrentUser>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getUserControllerGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create a new client
 */
export const clientControllerCreateClient = (
    createClientDto: CreateClientDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClientResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/clients`,
      createClientDto,options
    );
  }



export const getClientControllerCreateClientMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientControllerCreateClient>>, TError,{data: CreateClientDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof clientControllerCreateClient>>, TError,{data: CreateClientDto}, TContext> => {

const mutationKey = ['clientControllerCreateClient'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientControllerCreateClient>>, {data: CreateClientDto}> = (props) => {
          const {data} = props ?? {};

          return  clientControllerCreateClient(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClientControllerCreateClientMutationResult = NonNullable<Awaited<ReturnType<typeof clientControllerCreateClient>>>
    export type ClientControllerCreateClientMutationBody = CreateClientDto
    export type ClientControllerCreateClientMutationError = AxiosError<void>

    /**
 * @summary Create a new client
 */
export const useClientControllerCreateClient = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientControllerCreateClient>>, TError,{data: CreateClientDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof clientControllerCreateClient>>,
        TError,
        {data: CreateClientDto},
        TContext
      > => {

      const mutationOptions = getClientControllerCreateClientMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all clients (filtered by dietitian for non-admin)
 */
export const clientControllerGetClients = (
    params?: ClientControllerGetClientsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClientResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/clients`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getClientControllerGetClientsQueryKey = (params?: ClientControllerGetClientsParams,) => {
    return [
    `/api/v1/clients`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getClientControllerGetClientsQueryOptions = <TData = Awaited<ReturnType<typeof clientControllerGetClients>>, TError = AxiosError<unknown>>(params?: ClientControllerGetClientsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof clientControllerGetClients>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientControllerGetClientsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientControllerGetClients>>> = ({ signal }) => clientControllerGetClients(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientControllerGetClients>>, TError, TData> & { queryKey: QueryKey }
}

export type ClientControllerGetClientsQueryResult = NonNullable<Awaited<ReturnType<typeof clientControllerGetClients>>>
export type ClientControllerGetClientsQueryError = AxiosError<unknown>


/**
 * @summary Get all clients (filtered by dietitian for non-admin)
 */

export function useClientControllerGetClients<TData = Awaited<ReturnType<typeof clientControllerGetClients>>, TError = AxiosError<unknown>>(
 params?: ClientControllerGetClientsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof clientControllerGetClients>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getClientControllerGetClientsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Search clients by name or email
 */
export const clientControllerSearchClients = (
    params: ClientControllerSearchClientsParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClientResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/clients/search`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getClientControllerSearchClientsQueryKey = (params?: ClientControllerSearchClientsParams,) => {
    return [
    `/api/v1/clients/search`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getClientControllerSearchClientsQueryOptions = <TData = Awaited<ReturnType<typeof clientControllerSearchClients>>, TError = AxiosError<unknown>>(params: ClientControllerSearchClientsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof clientControllerSearchClients>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientControllerSearchClientsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientControllerSearchClients>>> = ({ signal }) => clientControllerSearchClients(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientControllerSearchClients>>, TError, TData> & { queryKey: QueryKey }
}

export type ClientControllerSearchClientsQueryResult = NonNullable<Awaited<ReturnType<typeof clientControllerSearchClients>>>
export type ClientControllerSearchClientsQueryError = AxiosError<unknown>


/**
 * @summary Search clients by name or email
 */

export function useClientControllerSearchClients<TData = Awaited<ReturnType<typeof clientControllerSearchClients>>, TError = AxiosError<unknown>>(
 params: ClientControllerSearchClientsParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof clientControllerSearchClients>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getClientControllerSearchClientsQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get client by ID
 */
export const clientControllerGetClientById = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClientResponseDto>> => {
    
    
    return axios.get(
      `/api/v1/clients/${id}`,options
    );
  }




export const getClientControllerGetClientByIdQueryKey = (id?: string,) => {
    return [
    `/api/v1/clients/${id}`
    ] as const;
    }

    
export const getClientControllerGetClientByIdQueryOptions = <TData = Awaited<ReturnType<typeof clientControllerGetClientById>>, TError = AxiosError<void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof clientControllerGetClientById>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getClientControllerGetClientByIdQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof clientControllerGetClientById>>> = ({ signal }) => clientControllerGetClientById(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof clientControllerGetClientById>>, TError, TData> & { queryKey: QueryKey }
}

export type ClientControllerGetClientByIdQueryResult = NonNullable<Awaited<ReturnType<typeof clientControllerGetClientById>>>
export type ClientControllerGetClientByIdQueryError = AxiosError<void>


/**
 * @summary Get client by ID
 */

export function useClientControllerGetClientById<TData = Awaited<ReturnType<typeof clientControllerGetClientById>>, TError = AxiosError<void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof clientControllerGetClientById>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getClientControllerGetClientByIdQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Update client
 */
export const clientControllerUpdateClient = (
    id: string,
    updateClientDto: UpdateClientDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ClientResponseDto>> => {
    
    
    return axios.put(
      `/api/v1/clients/${id}`,
      updateClientDto,options
    );
  }



export const getClientControllerUpdateClientMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientControllerUpdateClient>>, TError,{id: string;data: UpdateClientDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof clientControllerUpdateClient>>, TError,{id: string;data: UpdateClientDto}, TContext> => {

const mutationKey = ['clientControllerUpdateClient'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof clientControllerUpdateClient>>, {id: string;data: UpdateClientDto}> = (props) => {
          const {id,data} = props ?? {};

          return  clientControllerUpdateClient(id,data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ClientControllerUpdateClientMutationResult = NonNullable<Awaited<ReturnType<typeof clientControllerUpdateClient>>>
    export type ClientControllerUpdateClientMutationBody = UpdateClientDto
    export type ClientControllerUpdateClientMutationError = AxiosError<unknown>

    /**
 * @summary Update client
 */
export const useClientControllerUpdateClient = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof clientControllerUpdateClient>>, TError,{id: string;data: UpdateClientDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof clientControllerUpdateClient>>,
        TError,
        {id: string;data: UpdateClientDto},
        TContext
      > => {

      const mutationOptions = getClientControllerUpdateClientMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Create a new diet plan
 */
export const dietPlanControllerCreateDietPlan = (
    createDietPlanDto: CreateDietPlanDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DietPlanResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/diet-plans`,
      createDietPlanDto,options
    );
  }



export const getDietPlanControllerCreateDietPlanMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dietPlanControllerCreateDietPlan>>, TError,{data: CreateDietPlanDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof dietPlanControllerCreateDietPlan>>, TError,{data: CreateDietPlanDto}, TContext> => {

const mutationKey = ['dietPlanControllerCreateDietPlan'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dietPlanControllerCreateDietPlan>>, {data: CreateDietPlanDto}> = (props) => {
          const {data} = props ?? {};

          return  dietPlanControllerCreateDietPlan(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DietPlanControllerCreateDietPlanMutationResult = NonNullable<Awaited<ReturnType<typeof dietPlanControllerCreateDietPlan>>>
    export type DietPlanControllerCreateDietPlanMutationBody = CreateDietPlanDto
    export type DietPlanControllerCreateDietPlanMutationError = AxiosError<void>

    /**
 * @summary Create a new diet plan
 */
export const useDietPlanControllerCreateDietPlan = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dietPlanControllerCreateDietPlan>>, TError,{data: CreateDietPlanDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof dietPlanControllerCreateDietPlan>>,
        TError,
        {data: CreateDietPlanDto},
        TContext
      > => {

      const mutationOptions = getDietPlanControllerCreateDietPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all diet plans
 */
export const dietPlanControllerGetAllDietPlans = (
    params?: DietPlanControllerGetAllDietPlansParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DietPlanResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/diet-plans`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDietPlanControllerGetAllDietPlansQueryKey = (params?: DietPlanControllerGetAllDietPlansParams,) => {
    return [
    `/api/v1/diet-plans`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDietPlanControllerGetAllDietPlansQueryOptions = <TData = Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>, TError = AxiosError<unknown>>(params?: DietPlanControllerGetAllDietPlansParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDietPlanControllerGetAllDietPlansQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>> = ({ signal }) => dietPlanControllerGetAllDietPlans(params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>, TError, TData> & { queryKey: QueryKey }
}

export type DietPlanControllerGetAllDietPlansQueryResult = NonNullable<Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>>
export type DietPlanControllerGetAllDietPlansQueryError = AxiosError<unknown>


/**
 * @summary Get all diet plans
 */

export function useDietPlanControllerGetAllDietPlans<TData = Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>, TError = AxiosError<unknown>>(
 params?: DietPlanControllerGetAllDietPlansParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof dietPlanControllerGetAllDietPlans>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDietPlanControllerGetAllDietPlansQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all diet plans for a client
 */
export const dietPlanControllerGetDietPlansByClient = (
    clientId: string,
    params?: DietPlanControllerGetDietPlansByClientParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DietPlanResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/diet-plans/client/${clientId}`,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }




export const getDietPlanControllerGetDietPlansByClientQueryKey = (clientId?: string,
    params?: DietPlanControllerGetDietPlansByClientParams,) => {
    return [
    `/api/v1/diet-plans/client/${clientId}`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDietPlanControllerGetDietPlansByClientQueryOptions = <TData = Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>, TError = AxiosError<unknown>>(clientId: string,
    params?: DietPlanControllerGetDietPlansByClientParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDietPlanControllerGetDietPlansByClientQueryKey(clientId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>> = ({ signal }) => dietPlanControllerGetDietPlansByClient(clientId,params, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(clientId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>, TError, TData> & { queryKey: QueryKey }
}

export type DietPlanControllerGetDietPlansByClientQueryResult = NonNullable<Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>>
export type DietPlanControllerGetDietPlansByClientQueryError = AxiosError<unknown>


/**
 * @summary Get all diet plans for a client
 */

export function useDietPlanControllerGetDietPlansByClient<TData = Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>, TError = AxiosError<unknown>>(
 clientId: string,
    params?: DietPlanControllerGetDietPlansByClientParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof dietPlanControllerGetDietPlansByClient>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getDietPlanControllerGetDietPlansByClientQueryOptions(clientId,params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Activate a diet plan
 */
export const dietPlanControllerActivateDietPlan = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<DietPlanResponseDto>> => {
    
    
    return axios.put(
      `/api/v1/diet-plans/${id}/activate`,undefined,options
    );
  }



export const getDietPlanControllerActivateDietPlanMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dietPlanControllerActivateDietPlan>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof dietPlanControllerActivateDietPlan>>, TError,{id: string}, TContext> => {

const mutationKey = ['dietPlanControllerActivateDietPlan'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof dietPlanControllerActivateDietPlan>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  dietPlanControllerActivateDietPlan(id,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DietPlanControllerActivateDietPlanMutationResult = NonNullable<Awaited<ReturnType<typeof dietPlanControllerActivateDietPlan>>>
    
    export type DietPlanControllerActivateDietPlanMutationError = AxiosError<unknown>

    /**
 * @summary Activate a diet plan
 */
export const useDietPlanControllerActivateDietPlan = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof dietPlanControllerActivateDietPlan>>, TError,{id: string}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof dietPlanControllerActivateDietPlan>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getDietPlanControllerActivateDietPlanMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get all appointments
 */
export const appointmentControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/appointments`,options
    );
  }




export const getAppointmentControllerFindAllQueryKey = () => {
    return [
    `/api/v1/appointments`
    ] as const;
    }

    
export const getAppointmentControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof appointmentControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appointmentControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppointmentControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appointmentControllerFindAll>>> = ({ signal }) => appointmentControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appointmentControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type AppointmentControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof appointmentControllerFindAll>>>
export type AppointmentControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all appointments
 */

export function useAppointmentControllerFindAll<TData = Awaited<ReturnType<typeof appointmentControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appointmentControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppointmentControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create appointment
 */
export const appointmentControllerCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/appointments`,undefined,options
    );
  }



export const getAppointmentControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof appointmentControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['appointmentControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof appointmentControllerCreate>>, void> = () => {
          

          return  appointmentControllerCreate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AppointmentControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof appointmentControllerCreate>>>
    
    export type AppointmentControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create appointment
 */
export const useAppointmentControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof appointmentControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof appointmentControllerCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAppointmentControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get appointment by id
 */
export const appointmentControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/appointments/${id}`,options
    );
  }




export const getAppointmentControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/appointments/${id}`
    ] as const;
    }

    
export const getAppointmentControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof appointmentControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appointmentControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAppointmentControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof appointmentControllerFindOne>>> = ({ signal }) => appointmentControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof appointmentControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type AppointmentControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof appointmentControllerFindOne>>>
export type AppointmentControllerFindOneQueryError = AxiosError<unknown>


/**
 * @summary Get appointment by id
 */

export function useAppointmentControllerFindOne<TData = Awaited<ReturnType<typeof appointmentControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof appointmentControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAppointmentControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all foods
 */
export const foodControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/foods`,options
    );
  }




export const getFoodControllerFindAllQueryKey = () => {
    return [
    `/api/v1/foods`
    ] as const;
    }

    
export const getFoodControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof foodControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof foodControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFoodControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof foodControllerFindAll>>> = ({ signal }) => foodControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof foodControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type FoodControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof foodControllerFindAll>>>
export type FoodControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all foods
 */

export function useFoodControllerFindAll<TData = Awaited<ReturnType<typeof foodControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof foodControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFoodControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create food
 */
export const foodControllerCreate = (
    createFoodDto: CreateFoodDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/foods`,
      createFoodDto,options
    );
  }



export const getFoodControllerCreateMutationOptions = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof foodControllerCreate>>, TError,{data: CreateFoodDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof foodControllerCreate>>, TError,{data: CreateFoodDto}, TContext> => {

const mutationKey = ['foodControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof foodControllerCreate>>, {data: CreateFoodDto}> = (props) => {
          const {data} = props ?? {};

          return  foodControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type FoodControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof foodControllerCreate>>>
    export type FoodControllerCreateMutationBody = CreateFoodDto
    export type FoodControllerCreateMutationError = AxiosError<void>

    /**
 * @summary Create food
 */
export const useFoodControllerCreate = <TError = AxiosError<void>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof foodControllerCreate>>, TError,{data: CreateFoodDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof foodControllerCreate>>,
        TError,
        {data: CreateFoodDto},
        TContext
      > => {

      const mutationOptions = getFoodControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get food by id
 */
export const foodControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FoodResponseDto>> => {
    
    
    return axios.get(
      `/api/v1/foods/${id}`,options
    );
  }




export const getFoodControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/foods/${id}`
    ] as const;
    }

    
export const getFoodControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof foodControllerFindOne>>, TError = AxiosError<void>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof foodControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getFoodControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof foodControllerFindOne>>> = ({ signal }) => foodControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof foodControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type FoodControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof foodControllerFindOne>>>
export type FoodControllerFindOneQueryError = AxiosError<void>


/**
 * @summary Get food by id
 */

export function useFoodControllerFindOne<TData = Awaited<ReturnType<typeof foodControllerFindOne>>, TError = AxiosError<void>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof foodControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getFoodControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all meals
 */
export const mealControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MealResponseDto[]>> => {
    
    
    return axios.get(
      `/api/v1/meals`,options
    );
  }




export const getMealControllerFindAllQueryKey = () => {
    return [
    `/api/v1/meals`
    ] as const;
    }

    
export const getMealControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof mealControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof mealControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMealControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof mealControllerFindAll>>> = ({ signal }) => mealControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mealControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type MealControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof mealControllerFindAll>>>
export type MealControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all meals
 */

export function useMealControllerFindAll<TData = Awaited<ReturnType<typeof mealControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof mealControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getMealControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create meal
 */
export const mealControllerCreate = (
    createMealRequestDto: CreateMealRequestDto, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MealResponseDto>> => {
    
    
    return axios.post(
      `/api/v1/meals`,
      createMealRequestDto,options
    );
  }



export const getMealControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mealControllerCreate>>, TError,{data: CreateMealRequestDto}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof mealControllerCreate>>, TError,{data: CreateMealRequestDto}, TContext> => {

const mutationKey = ['mealControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof mealControllerCreate>>, {data: CreateMealRequestDto}> = (props) => {
          const {data} = props ?? {};

          return  mealControllerCreate(data,axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MealControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof mealControllerCreate>>>
    export type MealControllerCreateMutationBody = CreateMealRequestDto
    export type MealControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create meal
 */
export const useMealControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof mealControllerCreate>>, TError,{data: CreateMealRequestDto}, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof mealControllerCreate>>,
        TError,
        {data: CreateMealRequestDto},
        TContext
      > => {

      const mutationOptions = getMealControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get meal by id
 */
export const mealControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MealResponseDto>> => {
    
    
    return axios.get(
      `/api/v1/meals/${id}`,options
    );
  }




export const getMealControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/meals/${id}`
    ] as const;
    }

    
export const getMealControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof mealControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof mealControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMealControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof mealControllerFindOne>>> = ({ signal }) => mealControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof mealControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type MealControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof mealControllerFindOne>>>
export type MealControllerFindOneQueryError = AxiosError<unknown>


/**
 * @summary Get meal by id
 */

export function useMealControllerFindOne<TData = Awaited<ReturnType<typeof mealControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof mealControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getMealControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all metrics
 */
export const metricControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/metrics`,options
    );
  }




export const getMetricControllerFindAllQueryKey = () => {
    return [
    `/api/v1/metrics`
    ] as const;
    }

    
export const getMetricControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof metricControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof metricControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMetricControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof metricControllerFindAll>>> = ({ signal }) => metricControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof metricControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type MetricControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof metricControllerFindAll>>>
export type MetricControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all metrics
 */

export function useMetricControllerFindAll<TData = Awaited<ReturnType<typeof metricControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof metricControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getMetricControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create metric
 */
export const metricControllerCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/metrics`,undefined,options
    );
  }



export const getMetricControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof metricControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof metricControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['metricControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof metricControllerCreate>>, void> = () => {
          

          return  metricControllerCreate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type MetricControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof metricControllerCreate>>>
    
    export type MetricControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create metric
 */
export const useMetricControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof metricControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof metricControllerCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getMetricControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get metric by id
 */
export const metricControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/metrics/${id}`,options
    );
  }




export const getMetricControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/metrics/${id}`
    ] as const;
    }

    
export const getMetricControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof metricControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof metricControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getMetricControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof metricControllerFindOne>>> = ({ signal }) => metricControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof metricControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type MetricControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof metricControllerFindOne>>>
export type MetricControllerFindOneQueryError = AxiosError<unknown>


/**
 * @summary Get metric by id
 */

export function useMetricControllerFindOne<TData = Awaited<ReturnType<typeof metricControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof metricControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getMetricControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all audits
 */
export const auditControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/audits`,options
    );
  }




export const getAuditControllerFindAllQueryKey = () => {
    return [
    `/api/v1/audits`
    ] as const;
    }

    
export const getAuditControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof auditControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof auditControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditControllerFindAll>>> = ({ signal }) => auditControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type AuditControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof auditControllerFindAll>>>
export type AuditControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all audits
 */

export function useAuditControllerFindAll<TData = Awaited<ReturnType<typeof auditControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof auditControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuditControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create audit
 */
export const auditControllerCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/audits`,undefined,options
    );
  }



export const getAuditControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof auditControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['auditControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof auditControllerCreate>>, void> = () => {
          

          return  auditControllerCreate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AuditControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof auditControllerCreate>>>
    
    export type AuditControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create audit
 */
export const useAuditControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof auditControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof auditControllerCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getAuditControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get audit by id
 */
export const auditControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/audits/${id}`,options
    );
  }




export const getAuditControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/audits/${id}`
    ] as const;
    }

    
export const getAuditControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof auditControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof auditControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAuditControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof auditControllerFindOne>>> = ({ signal }) => auditControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof auditControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type AuditControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof auditControllerFindOne>>>
export type AuditControllerFindOneQueryError = AxiosError<unknown>


/**
 * @summary Get audit by id
 */

export function useAuditControllerFindOne<TData = Awaited<ReturnType<typeof auditControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof auditControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getAuditControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all events
 */
export const eventControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/events`,options
    );
  }




export const getEventControllerFindAllQueryKey = () => {
    return [
    `/api/v1/events`
    ] as const;
    }

    
export const getEventControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerFindAll>>> = ({ signal }) => eventControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type EventControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerFindAll>>>
export type EventControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all events
 */

export function useEventControllerFindAll<TData = Awaited<ReturnType<typeof eventControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getEventControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create event
 */
export const eventControllerCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/events`,undefined,options
    );
  }



export const getEventControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['eventControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof eventControllerCreate>>, void> = () => {
          

          return  eventControllerCreate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type EventControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof eventControllerCreate>>>
    
    export type EventControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create event
 */
export const useEventControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof eventControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof eventControllerCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getEventControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get event by id
 */
export const eventControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/events/${id}`,options
    );
  }




export const getEventControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/events/${id}`
    ] as const;
    }

    
export const getEventControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getEventControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof eventControllerFindOne>>> = ({ signal }) => eventControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type EventControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof eventControllerFindOne>>>
export type EventControllerFindOneQueryError = AxiosError<unknown>


/**
 * @summary Get event by id
 */

export function useEventControllerFindOne<TData = Awaited<ReturnType<typeof eventControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof eventControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getEventControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Get all reports
 */
export const reportControllerFindAll = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/reports`,options
    );
  }




export const getReportControllerFindAllQueryKey = () => {
    return [
    `/api/v1/reports`
    ] as const;
    }

    
export const getReportControllerFindAllQueryOptions = <TData = Awaited<ReturnType<typeof reportControllerFindAll>>, TError = AxiosError<unknown>>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reportControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportControllerFindAllQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportControllerFindAll>>> = ({ signal }) => reportControllerFindAll({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportControllerFindAll>>, TError, TData> & { queryKey: QueryKey }
}

export type ReportControllerFindAllQueryResult = NonNullable<Awaited<ReturnType<typeof reportControllerFindAll>>>
export type ReportControllerFindAllQueryError = AxiosError<unknown>


/**
 * @summary Get all reports
 */

export function useReportControllerFindAll<TData = Awaited<ReturnType<typeof reportControllerFindAll>>, TError = AxiosError<unknown>>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reportControllerFindAll>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReportControllerFindAllQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}





/**
 * @summary Create report
 */
export const reportControllerCreate = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.post(
      `/api/v1/reports`,undefined,options
    );
  }



export const getReportControllerCreateMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof reportControllerCreate>>, TError,void, TContext> => {

const mutationKey = ['reportControllerCreate'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof reportControllerCreate>>, void> = () => {
          

          return  reportControllerCreate(axiosOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ReportControllerCreateMutationResult = NonNullable<Awaited<ReturnType<typeof reportControllerCreate>>>
    
    export type ReportControllerCreateMutationError = AxiosError<unknown>

    /**
 * @summary Create report
 */
export const useReportControllerCreate = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof reportControllerCreate>>, TError,void, TContext>, axios?: AxiosRequestConfig}
 ): UseMutationResult<
        Awaited<ReturnType<typeof reportControllerCreate>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getReportControllerCreateMutationOptions(options);

      return useMutation(mutationOptions);
    }
    
/**
 * @summary Get report by id
 */
export const reportControllerFindOne = (
    id: string, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.get(
      `/api/v1/reports/${id}`,options
    );
  }




export const getReportControllerFindOneQueryKey = (id?: string,) => {
    return [
    `/api/v1/reports/${id}`
    ] as const;
    }

    
export const getReportControllerFindOneQueryOptions = <TData = Awaited<ReturnType<typeof reportControllerFindOne>>, TError = AxiosError<unknown>>(id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reportControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getReportControllerFindOneQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof reportControllerFindOne>>> = ({ signal }) => reportControllerFindOne(id, { signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof reportControllerFindOne>>, TError, TData> & { queryKey: QueryKey }
}

export type ReportControllerFindOneQueryResult = NonNullable<Awaited<ReturnType<typeof reportControllerFindOne>>>
export type ReportControllerFindOneQueryError = AxiosError<unknown>


/**
 * @summary Get report by id
 */

export function useReportControllerFindOne<TData = Awaited<ReturnType<typeof reportControllerFindOne>>, TError = AxiosError<unknown>>(
 id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof reportControllerFindOne>>, TError, TData>, axios?: AxiosRequestConfig}
  
 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getReportControllerFindOneQueryOptions(id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
